/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ImageSegmentation */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     ImageSegmentation
	 * Method:    KmeansSegmentation
	 * Signature: (Ljava/lang/String;II)V
	 */
	JNIEXPORT void JNICALL Java_application_Main_KmeansSegmentation
	(JNIEnv*, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
